---
title: "Warfarin Dosing Service Storyboard"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(BGTools)
library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)
library(ggplot2)
library(scales)
library(tableone)
tmp <- get_rds("tidy")
tmp <- get_rds("analysis")
pts.include <- inner_join(pts.include, data.new, by = "pie.id")
```

### Dosing Service Utilization

```{r}
d <- analyze.utilization %>%
    spread(order, n) %>%
    mutate(warfarin = ifelse(is.na(consult), warfarin, warfarin - consult)) %>%
    gather(order, n, -action.date) %>%
    arrange(action.date)

ggplot(d, aes(x = action.date, y = n, color = order)) +
    geom_line(size = 0.2, alpha = 0.7) +
    geom_smooth() +
    ggtitle("Daily Warfarin Orders Managed by Pharmacy and Traditional") +
    xlab("Date") +
    ylab("Number of Daily Orders") +
    scale_color_brewer(palette = "Set1", labels = c("Pharmacy", "Traditional"), guide = guide_legend(title = NULL)) 
# +
    # xlim(c(mdy_hm("1/1/2013 00:00"), mdy_hm("12/31/2015 23:59")))
```

***
The number of warfarin patients managed each day by the pharmacy dosing service and traditional warfarin dosing.

### Medical Services Ordering Warfarin

```{r}
d <- analyze.services.all %>%
    mutate(service = ordered(service, levels = names(sort(table(service), decreasing = TRUE)))) %>%
    group_by(service) %>%
    summarize(count = n()) %>%
    arrange(desc(count)) %>%
    top_n(10, count)

g <- ggplot(d, aes(x = service, y = count)) +
    geom_bar(stat = "identity", fill = "#1F78B4") +
    ggtitle("Top 10 Medical Services Utilizing Warfarin") +
    xlab("Medical Service") +
    ylab("Number of Patients") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

print(g)
```

***
Utilization of warfarin by medical service

### INR Response

```{r}
d <- pts.include %>%
    inner_join(data.labs.inrs, by = "pie.id") %>%
    calc_lab_runtime(units = "days") %>%
    filter(year == "current")

g <- ggplot(d, aes(x = run.time, y = lab.result, group = group)) +
    geom_point(alpha = 0.3, size = 0.5) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "dark blue") +
    geom_smooth(aes(color = group)) +
    ggtitle("INR response after starting warfarin") +
    xlab("Day") +
    ylab("INR") +
    scale_x_continuous(breaks = seq(-2, 10, by = 2)) +
    scale_color_brewer(palette = "Set1", labels = c("Pharmacy", "Traditional"), guide = guide_legend(title = NULL)) +
    coord_cartesian(xlim = c(-2, 10), ylim = c(1, 3))

print(g)
```

***
INR response to warfarin dosing by group. Notice how the curves separate after day 3. 
