---
title: "Warfarin Dosing Service Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(edwr)
library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)
library(ggplot2)
library(scales)
library(tableone)

data.raw <- "data/raw"

# get all warfarin and consult orders
data.orders <- read_data(data.raw, "orders") %>%
    as.order_by() %>%
    filter(action.type == "Order") %>%
    mutate(action.date = floor_date(action.datetime, unit = "day"),
           consult = !str_detect(order, "^warfarin$"))

# make tidy data set
df <- data.orders %>%
    distinct(pie.id, action.date, consult) %>%
    group_by(pie.id, action.date) %>%
    mutate(value = TRUE,
           consult = if_else(consult == TRUE, "consult", "warfarin")) %>%
    spread(consult, value) %>%
    mutate(warfarin = if_else(consult == TRUE & is.na(warfarin), TRUE, warfarin)) %>%
    gather(order, value, consult, warfarin) %>%
    filter(!is.na(value)) %>%
    group_by(pie.id, action.date, order) %>%
    summarize(n = n()) %>%
    group_by(action.date, order) %>%
    summarize(n = n()) %>%
    spread(order, n) %>%
    mutate(warfarin = if_else(is.na(consult), warfarin, warfarin - consult)) %>%
    gather(order, n, -action.date) %>%
    mutate(n = coalesce(n, 0L))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Dosing Service Utilization

```{r}
ggplot(df, aes(x = action.date, y = n, color = order)) +
    geom_line(size = 0.2, alpha = 0.7) +
    geom_smooth() +
    ggtitle("Daily Warfarin Orders Managed by Pharmacy and Traditional") +
    xlab("Date") +
    ylab("Number of Daily Orders") +
    scale_color_brewer(palette = "Set1", labels = c("Pharmacy", "Traditional"), guide = guide_legend(title = NULL)) 
# +
    # xlim(c(mdy_hm("1/1/2013 00:00"), mdy_hm("12/31/2015 23:59")))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
# d <- analyze.services.all %>%
#     mutate(service = ordered(service, levels = names(sort(table(service), decreasing = TRUE)))) %>%
#     group_by(service) %>%
#     summarize(count = n()) %>%
#     arrange(desc(count)) %>%
#     top_n(10, count)
# 
# g <- ggplot(d, aes(x = service, y = count)) +
#     geom_bar(stat = "identity", fill = "#1F78B4") +
#     ggtitle("Top 10 Medical Services Utilizing Warfarin") +
#     xlab("Medical Service") +
#     ylab("Number of Patients") +
#     theme(axis.text.x = element_text(angle = 45, hjust = 1))
# 
# print(g)
```

### Chart C

```{r}
# d <- pts.include %>%
#     inner_join(data.labs.inrs, by = "pie.id") %>%
#     calc_lab_runtime(units = "days") %>%
#     filter(year == "current")
# 
# g <- ggplot(d, aes(x = run.time, y = lab.result, group = group)) +
#     geom_point(alpha = 0.3, size = 0.5) +
#     geom_vline(xintercept = 0, linetype = "dashed", color = "dark blue") +
#     geom_smooth(aes(color = group)) +
#     ggtitle("INR response after starting warfarin") +
#     xlab("Day") +
#     ylab("INR") +
#     scale_x_continuous(breaks = seq(-2, 10, by = 2)) +
#     scale_color_brewer(palette = "Set1", labels = c("Pharmacy", "Traditional"), guide = guide_legend(title = NULL)) +
#     coord_cartesian(xlim = c(-2, 10), ylim = c(1, 3))
# 
# print(g)
```

